version: "3.9"

services:
  app:
    #image: simple-agent-app
    image: subuppaluru71/simple-agent-app:latest
    build: .
    ports:
      - "8501:8501"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    restart: unless-stopped
