apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-agent-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
    - host: agent.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simple-agent-service
                port:
                  number: 80
