apiVersion: v1
kind: Secret
metadata:
  name: agent-secrets
type: Opaque
data:
  OPENAI_API_KEY: c2stcHJvai11a1F4cnlTYXBobHprM0ZPVldhdGtxTV9LNmhDTmtzTk0zWEZOZDdvNGdIaVg5eWJoREtMWXpfR3ZWNGNQd2hyZUhJN3hGZFM1Q1QzQmxia0ZKRG0zSXFEVUlVV0Ewc1ZPRVhvYmpXaWxvOEh4YTRJYk9DSUdxVk9mdzdieGxrRWdYdVRVd0dGNU1hNXZCU2NleEI2VHZKRVJib0E=
